import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parent.parent))

import copy
import evaluate
import torch
from tqdm import tqdm
from datasets import load_dataset
from torch.utils.data import DataLoader
from transformers import AutoTokenizer, T5ForConditionalGeneration, DataCollatorForSeq2Seq
from peft import PeftModel
from utils import SummarizeEncoder, load_config, instantiate_logger, get_default_device, save_to_jsonl


logger = instantiate_logger("Test")

logger.info("Load Test Config")
config = load_config("config_lora.yaml", "test")

def pack_sentence_summary_generated(sentence_text, summary_text, generated):
    
    output = []
    for i in range(len(generated)):
        element = {}
        element['sentence'] = sentence_text[i]
        element['summary'] = summary_text[i]
        element['generated_summary'] = tokenizer.decode(generated[i], skip_special_tokens=True)
        output.append(element)

    return output


def predict_summary(model, data_loader, num_batch = 100):
    
    output = []
    model.eval()
    with torch.no_grad():
        process_pbar = tqdm(data_loader, leave=True, total=num_batch)
        for i, batch_data in enumerate(process_pbar):

            if i>num_batch-1:
                break

            original_text = tokenizer.batch_decode(batch_data['input_ids'], skip_special_tokens=True)
            summary_tokens = copy.deepcopy(batch_data['labels'])
            summary_tokens[summary_tokens == -100]=tokenizer.pad_token_id
            summary_text = tokenizer.batch_decode(summary_tokens, skip_special_tokens=True)
            input_ids, attention_mask  = batch_data["input_ids"], batch_data["attention_mask"]
            input_ids = input_ids.to(device)
            attention_mask = attention_mask.to(device)
            generated = model.generate(input_ids=input_ids, 
                                       attention_mask=attention_mask, 
                                       max_length=170, 
                                       min_length=40, 
                                       length_penalty=2.0, 
                                       num_beams=4, 
                                       early_stopping=True)
            
            # for this function will will include the generated by model summary and the gold standard summary, for easy of use later
            sub_output = pack_sentence_summary_generated(original_text, summary_text, generated)
            output += sub_output
            process_pbar.set_description("Progress")

            
    return output


if __name__ == "__main__":

    logger.info("Load Test Data")
    data_files = {"test": config.test_data_paths}
    dataset = load_dataset('json', data_files=data_files, streaming=True)
    test_dataset = dataset["test"]

    logger.info("Preprocess Test Data")
    # Load tokenizer
    tokenizer = AutoTokenizer.from_pretrained(config.base_model_checkpoint)
    summarizer_encoder = SummarizeEncoder(tokenizer = tokenizer, encoder_max_len=config.encoder_max_len)

    columns_remove = list(test_dataset.features.keys())
    test_dataset = test_dataset.map(summarizer_encoder.encode, remove_columns = columns_remove)

    data_collator = DataCollatorForSeq2Seq(tokenizer = tokenizer)
    test_dl = DataLoader(test_dataset, batch_size=config.batch_size, collate_fn=data_collator)

    logger.info("Load Model")
    device = get_default_device()

    base_model = T5ForConditionalGeneration.from_pretrained(config.base_model_checkpoint)
    base_model = base_model.to(device)

    logger.info("Construct peft model")
    model = PeftModel.from_pretrained(base_model, config.adapter_path)
    model.eval()

    logger.info("Begin Prediction")
    test_result = predict_summary(model, test_dl, num_batch = config.num_batch)

    logger.info("Save Prediction Results")
    save_to_jsonl(test_result, outfile= config.outfile)
    # using evaluate and rouge-score python package

    logger.info("Begin Evaluation")
    rouge = evaluate.load("rouge")

    gold_summary = []
    gen_summary = []

    for item in test_result:
        gold_summary.append(item['summary'].replace('\r\n','').replace('\n',''))
        gen_summary.append(item['generated_summary'])

    result = rouge.compute(predictions=gen_summary, references=gold_summary, use_stemmer=True)
    print({k: round(v, 4) for k,v in result.items()})